package com.app.core;

/** A point generated by the producer. */
public class Point {
	private final int xPoint;
	private final double yPoint;

	public Point(int xPoint, double yPoint) {
		this.xPoint = xPoint;
		this.yPoint = yPoint;
	}

	public int getXPoint() {
		return xPoint;
	}

	public double getYPoint() {
		return yPoint;
	}

	@Override
	public String toString() {
		return "Point{xPoint=" + xPoint + ", yPoint=" + yPoint + '}';
	}
}
